const userEndpoints = {
    userSignUp: '/user/verifyMail',
    userForgotPassword: '/user/forgotPassword',
    userVerifyOtp: '/user/verifyOtp',
    userVerifyOtpForgotPassword: '/user/verifyOtpForgotPassword',
    userResendOtp: '/user/resendOtp',
    userResetPassword: '/user/resetPassword',
    userLogin: '/user/login',
    userLogout: '/user/logout',
    userGsignup: '/user/gsignup',
    userProfile: '/user/profile',
    userEditProfile: '/user/editprofile',
    userNewConversation: '/chat/newConversation',
    userGetMessages: '/chat/getMessages',
    userNewMessage: '/chat/newMessage',
    userNewImageMessage: '/chat/newImageMessage',
    userNewVideoMessage: '/chat/newVideoMessage',
    userBook: '/book/newBooking',
    userGetCheckout: '/book/getCheckout',
    userProceedForPayment: '/book/proceedForPayment',
    userSaveSession: '/book/saveSession',
    userGetBookings: '/book/getBookings',
    userCancel: '/book/cancelBooking',
    userFetchPackage: '/user/fetchPackage',
    singlePackage: (id: string) => `/user/singlePackage/${id}`,
    getCheckout: (bookingId: string) => `/book/getCheckout/${bookingId}`,
    userRate: '/user/rate',
    userRateExist: '/user/rateExist',
    userGetRatings: '/user/getRatings',
    getProvider: '/user/getProvider',
    findRateById: '/user/findRateById',
    editRate: '/user/editRate',
    getBookingDetails: '/user/getBookingDetails',
    findUser: '/user/findUser'

}
export default userEndpoints